In [1]:
import random
import numpy as np
from ifsgen.vertices import SIMPLEX
from typing import Callable
import plotly.graph_objects as go

In [42]:
a = np.array([0, 2])
b = np.array([8, 8])

In [45]:
def point_at_percent_distance(A, B, d):
    """
    Calculate a point at a percentage distance d between two points A and B.

    Parameters:
    A (np.ndarray): Starting point.
    B (np.ndarray): Ending point.
    d (float): Percentage distance from A to B (0 <= d <= 1).

    Returns:
    np.ndarray: Point at distance d between A and B.
    """
    return A + (d * (B - A))

In [46]:
point_at_percent_distance(a, b, 0.5)

array([4., 5.])

In [34]:
def midpoint(A, B, d):
    return (A + B) * d

In [28]:
midpoint(a, b, 0.5)

array([4., 5.])

In [30]:
midpoint(a, b, 0.05)

array([0.4, 0.5])

In [6]:
bool((a == b).all())

True

In [21]:
class IFS:
    def __init__(
        self,
        midpoint: Callable[[np.ndarray, np.ndarray], np.ndarray],
        selector: Callable[
            [list[np.ndarray]], np.ndarray
        ],  # todo: add selection history
        vertices: list[np.ndarray],
    ) -> None:
        self.midpoint = midpoint
        self.selector = selector
        self.vertices = vertices

    @property
    def dimensions(self) -> int:
        return len(self.vertices[0])

    def run(self, n: int):
        points = [np.zeros(self.dimensions)]
        for i in range(n):
            points.append(self.midpoint(points[i], self.selector(self.vertices)))
        return points

In [24]:
def midpoint(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    return (x + y) / 2


def selector(vertices: list[np.ndarray]) -> np.ndarray:
    return random.choice(vertices)


ifs = IFS(midpoint=midpoint, selector=selector, vertices=SIMPLEX[2])

In [25]:
ifs.run(1000)

[array([0., 0.]),
 array([-0.25      , -0.21650635]),
 array([-0.375     , -0.32475953]),
 array([-0.4375    , -0.37888611]),
 array([-0.21875   ,  0.02706329]),
 array([ 0.140625 , -0.2029747]),
 array([ 0.3203125, -0.3179937]),
 array([0.16015625, 0.0575095 ]),
 array([0.08007812, 0.2452611 ]),
 array([0.04003906, 0.3391369 ]),
 array([ 0.27001953, -0.0469379 ]),
 array([0.13500977, 0.1930374 ]),
 array([ 0.31750488, -0.11998765]),
 array([0.15875244, 0.15651253]),
 array([ 0.32937622, -0.13825009]),
 array([0.16468811, 0.14738131]),
 array([-0.16765594, -0.1428157 ]),
 array([-0.08382797,  0.1450985 ]),
 array([ 0.20808601, -0.1439571 ]),
 array([0.10404301, 0.1445278 ]),
 array([-0.1979785 , -0.14424245]),
 array([ 0.15101075, -0.28862758]),
 array([ 0.32550538, -0.36082014]),
 array([ 0.41275269, -0.39691642]),
 array([-0.04362366, -0.41496456]),
 array([-0.02181183,  0.00902407]),
 array([-0.26090591, -0.21199432]),
 array([ 0.11954704, -0.32250351]),
 array([ 0.30977352, -0.3777

In [ ]:
fig = go.Figure(data=)