In [13]:
import random
import numpy as np
from ifsgen.vertices import SIMPLEX
from typing import Callable

In [14]:
l = [1, 2, 3]

In [15]:
random.choice(l)

2

In [17]:
class IFS:
    def __init__(
        self,
        midpoint: Callable[[np.ndarray, np.ndarray], np.ndarray],
        selector: Callable[
            [list[np.ndarray]], np.ndarray
        ],  # todo: add selection history
        vertices: list[np.ndarray],
    ) -> None:
        self.midpoint = midpoint
        self.selector = selector
        self.vertices = vertices

    @property
    def dimensions(self) -> int:
        return len(self.vertices[0])

    def run(self, n: int):
        points = [np.zeros(self.dimensions)]
        for i in range(n):
            points.append(self.midpoint(points[i], self.selector(self.vertices)))
        return points

In [18]:
def midpoint(x: np.ndarray, y: np.ndarray) -> np.ndarray:
    return (x + y) / 2


def selector(vertices: list[np.ndarray]) -> np.ndarray:
    return random.choice(vertices)


ifs = IFS(midpoint=midpoint, selector=selector, vertices=SIMPLEX[3])

In [19]:
ifs.run(100)

[array([0., 0., 0.]),
 array([0. , 0. , 0.5]),
 array([0.  , 0.  , 0.75]),
 array([-0.23570226, -0.40824829,  0.20833333]),
 array([-0.35355339, -0.61237244, -0.0625    ]),
 array([-0.41247896, -0.71443451, -0.19791667]),
 array([ 0.26516504, -0.35721725, -0.265625  ]),
 array([ 0.13258252, -0.17860863,  0.3671875 ]),
 array([ 0.53769578, -0.08930431,  0.01692708]),
 array([ 0.26884789, -0.04465216,  0.50846354]),
 array([ 0.13442395, -0.02232608,  0.75423177]),
 array([-0.16849029, -0.41941133,  0.21044922]),
 array([ 0.38715938, -0.20970566, -0.06144206]),
 array([ 0.66498421, -0.10485283, -0.1973877 ]),
 array([ 0.09678984,  0.35582187, -0.26536051]),
 array([0.04839492, 0.17791094, 0.36731974]),
 array([0.02419746, 0.08895547, 0.68365987]),
 array([0.48350325, 0.04447773, 0.17516327]),
 array([ 0.00604937,  0.43048716, -0.07908503]),
 array([-0.23267758, -0.19300471, -0.20620918]),
 array([-0.11633879, -0.09650236,  0.39689541]),
 array([ 0.41323513, -0.04825118,  0.03178104]),
 ar